### ISSUE TITLE
Listing Orders Received

### ISSUE THREAD

**Issue by esurerer** [GlobalFood/integration_docs#10]
Hello there,

I can access the menu data in the system via the address https://pos.globalfoodsoft.com/pos/menu. But I request your help to pull the orders received.

In the simplest form, how can I integrate orders into my pos system?
Platform Winform c #

When I want to list the order with the address https://pos.globalfoodsoft.com/pos/order/pop, the following value returns.
```
{
     "count": 0,
     "orders": []
}
```

Thank you.

**Comment by uwleahcim** [comment]
I'm having similar issues trying to poll for orders (always return count of 0). Did you ever figure out the issue?

**Comment by soljancic** [comment]
only return the new orders, once you read de webservice the order wont return again
