### ISSUE TITLE
Accept order with delivertime via API. Possible?

### ISSUE THREAD

**Issue by tueddy** [GlobalFood/integration_docs#11]
Hi GloriaFood API-Team,

first thanks for clean API and good description. We have connected our POS successfully!
Now we want to accept (or reject) new orders directly in our POS. Is there an API for that?

Thank's in advance
Dirk

**Comment by tueddy** [comment]
Any answer here?
Thank's
Dirk

**Comment by olavomuller** [comment]
do you find it? If yes, share us. Thanks

**Comment by sinfield057** [comment]
This is just a public documentation page. Please submit such requests to [contact@globalfoodsoft.com](mailto:contact@globalfoodsoft.com) and specify the exact use case your planning on implementing with this support.
