### ISSUE TITLE
Requesting full list of order

### ISSUE THREAD

**Issue by diegopennesi** [GlobalFood/integration_docs#14]
I have an issue retriving order from API.
Fetching menù is easy, but i can't rly grasp the flow of application about reciving order.
Saw the isse open back in 2020 but when i read documentation, i can see the status filed whit various status for order, so i can actualy retrive all order, even if i already accepted.
I recive an emty list even if i place a request via web (not a mock one via application).
i need to have a list of today order in order to agglomerate via table and label as pay on my side.
example
Customer A sit table 1, order 2 beer, then leave after 60m and proceed to pay cash.
FIne i will have 1 order easy to search.
Customer B sit table 1, order 1 beer, then after 20m order another beer. 
Two orders are made, table 1 again.

Now i can't know if Customer B  must pay 2 beers or 4 since there is no pay label.
OK, i can leave the Customer B on In progress whit 900minute and then calculate maually how much she\he must pay (a very ugly solution).

It would be better for me to retrive order when they are accepted and then manipulate whidout sending anything to syststem, and then after the client walks away to label order as completed via app.

Would be possible?
I think it would be possible, but via Postam i recive a response 200 whit order 0 and emnpty array.

Sincerely
Diego

**Comment by sinfield057** [comment]
This is just a public documentation page. Please submit such requests to [contact@globalfoodsoft.com](mailto:contact@globalfoodsoft.com) and specify the exact use case your planning on implementing with this support.
