### ISSUE TITLE
User should be able to order through API

### ISSUE THREAD

**Issue by sebitoelcheater** [GlobalFood/integration_docs#5]
A user should be able to POST new orders through the API.

**Comment by lebnd** [comment]
This is just a public documentation page. Please submit such requests to contact@globalfoodsoft.com and specify the exact use case your planning on implementing with this support.

**Comment by SagarDhiman018** [comment]
Hi @sebitoelcheater and all, did you find the order through API 

> A user should be able to POST new orders through the API.

Hi @sebitoelcheater @tenxliviu , is there any solution for the above query my requirement is also the same `A user should be able to POST new orders through the API `?  Your response will be appreciated Thanks!
